# Generated by Django 3.0 on 2019-12-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrow',
            new_name='borrower',
        ),
    ]
