# Generated by Django 3.0 on 2019-12-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191219_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_borrowed_books', 'one can view all borrowed books'),)},
        ),
    ]
